on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: |
          git clone https://github.com/armbian/build.git
          cp ./files/config/boards/mkspi.conf ./build/config/boards/
          cp -r ./files/userpatches/ build
          cd build
          ./compile.sh  BOARD=mkspi BRANCH=current RELEASE=jammy BSPFREEZE=yes BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,gpg,img KERNEL_GIT=full PROGRESS_LOG_TO_FILE=yes PROGRESS_DISPLAY=plain CLEAN_LEVEL=make,debs,make-uboot INCLUDE_HOME_DIR=yes
          LOOP_DEV=$(sudo losetup --partscan --find --show ./output/images/*.img)
          sudo mount "$LOOP_DEV"p2 /mnt
          cp /mnt/home/mks/versions ..
          sudo umount /mnt

      - name: Archiving artifacts
        run: cd build && zip -r output.zip output

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: 'Release'
          body_path: versions
          draft: false
          prerelease: false

      - name: Upload files to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/output.zip
          asset_name: output.zip
          asset_content_type: application/zip

